### ISSUE TITLE
v1.0.0 broke Clojure 1.7.0 compatibility for no good reason (IMO)

### ISSUE THREAD

**Issue by darwin** [funcool/cuerdas#38]
It started using `clojure.string/includes?` which is available since Clojure 1.8.0.

https://github.com/funcool/cuerdas/blob/master/src/cuerdas/core.cljc#L298

I would propose to implement a backport version and use it with Clojure 1.7 and below:
https://github.com/binaryage/dirac/blob/master/src/backport/dirac/backport/string.clj

```
Exception in thread "main" java.lang.RuntimeException: No such var: str/includes?, compiling:(cuerdas/core.cljc:298:5)
       	at clojure.lang.Compiler.analyze(Compiler.java:6543)
       	at clojure.lang.Compiler.analyze(Compiler.java:6485)
       	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3737)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6725)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyze(Compiler.java:6485)
       	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyze(Compiler.java:6485)
       	at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2785)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyze(Compiler.java:6485)
       	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
       	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
       	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.access$300(Compiler.java:38)
       	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
       	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
       	at clojure.lang.Compiler.analyze(Compiler.java:6524)
       	at clojure.lang.Compiler.analyze(Compiler.java:6485)
       	at clojure.lang.Compiler.eval(Compiler.java:6786)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:457)
       	at dirac.logging.utils$eval14642$loading__5340__auto____14643.invoke(utils.clj:1)
       	at dirac.logging.utils$eval14642.invoke(utils.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:436)
       	at dirac.logging$eval14636$loading__5340__auto____14637.invoke(logging.clj:1)
       	at dirac.logging$eval14636.invoke(logging.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:482)
       	at dirac.lib.ws_server$eval14600$loading__5340__auto____14601.invoke(ws_server.clj:2)
       	at dirac.lib.ws_server$eval14600.invoke(ws_server.clj:2)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:512)
       	at dirac.lib.weasel_server$eval8900$loading__5340__auto____8901.invoke(weasel_server.clj:2)
       	at dirac.lib.weasel_server$eval8900.invoke(weasel_server.clj:2)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:551)
       	at dirac.nrepl$eval8894$loading__5340__auto____8895.invoke(nrepl.clj:1)
       	at dirac.nrepl$eval8894.invoke(nrepl.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:482)
       	at dirac.test.nrepl_server_helpers$eval7710$loading__5340__auto____7711.invoke(nrepl_server_helpers.clj:1)
       	at dirac.test.nrepl_server_helpers$eval7710.invoke(nrepl_server_helpers.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:703)
       	at dirac.agent_tests$eval70$loading__5340__auto____71.invoke(agent_tests.clj:1)
       	at dirac.agent_tests$eval70.invoke(agent_tests.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:482)
       	at dirac.backend_tests_runner$eval20$loading__5340__auto____21.invoke(backend_tests_runner.clj:1)
       	at dirac.backend_tests_runner$eval20.invoke(backend_tests_runner.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6771)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.RT.loadResourceScript(RT.java:371)
       	at clojure.lang.RT.loadResourceScript(RT.java:362)
       	at clojure.lang.RT.load(RT.java:446)
       	at clojure.lang.RT.load(RT.java:412)
       	at clojure.core$load$fn__5448.invoke(core.clj:5866)
       	at clojure.core$load.doInvoke(core.clj:5865)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at clojure.core$load_one.invoke(core.clj:5671)
       	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
       	at clojure.core$load_lib.doInvoke(core.clj:5710)
       	at clojure.lang.RestFn.applyTo(RestFn.java:142)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$load_libs.doInvoke(core.clj:5749)
       	at clojure.lang.RestFn.applyTo(RestFn.java:137)
       	at clojure.core$apply.invoke(core.clj:632)
       	at clojure.core$require.doInvoke(core.clj:5832)
       	at clojure.lang.RestFn.invoke(RestFn.java:408)
       	at user$eval5$fn__7.invoke(form-init4573647278826304707.clj:1)
       	at user$eval5.invoke(form-init4573647278826304707.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6782)
       	at clojure.lang.Compiler.eval(Compiler.java:6772)
       	at clojure.lang.Compiler.load(Compiler.java:7227)
       	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
       	at clojure.main$load_script.invoke(main.clj:275)
       	at clojure.main$init_opt.invoke(main.clj:280)
       	at clojure.main$initialize.invoke(main.clj:308)
       	at clojure.main$null_opt.invoke(main.clj:343)
       	at clojure.main$main.doInvoke(main.clj:421)
       	at clojure.lang.RestFn.invoke(RestFn.java:421)
       	at clojure.lang.Var.invoke(Var.java:383)
       	at clojure.lang.AFn.applyToHelper(AFn.java:156)
       	at clojure.lang.Var.applyTo(Var.java:700)
       	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No such var: str/includes?
       	at clojure.lang.Util.runtimeException(Util.java:221)
       	at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
       	at clojure.lang.Compiler.resolve(Compiler.java:6963)
       	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
       	at clojure.lang.Compiler.analyze(Compiler.java:6506)
       	... 238 more
Error encountered performing task 'run' with profile(s): 'base,system,user,provided,dev,test-runner,clojure17'
Suppressed exit
```

**Comment by niwinz** [comment]
I agree! I'll fix it ASAP.

**Comment by niwinz** [comment]
Should be fixed in 1.0.1, thanks again ;)

**Comment by niwinz** [comment]
I'll go to setup the test suite to run again clojure 1.7 in order to prevent this kind of bugs.

**Comment by darwin** [comment]
v1.0.1 works for me. Thanks for quick resolution!
