### ISSUE TITLE
Tests documentation is outdated

### ISSUE THREAD

**Issue by bfontaine** [funcool/cuerdas#75]
Hello, I’m trying to run the tests but the documentation is outdated: https://github.com/funcool/cuerdas/blob/master/doc/content.adoc#run-tests

> Run tests in the Clojure environment using Leiningen.
>
>     $ lein test cuerdas.core-tests
>
> Compile ClojureScript to JavaScript.
>
>     $ ./scripts/build

On the latest master:

```
$ lein test cuerdas.core-tests
Couldn't find project.clj, which is needed for test

$ ./scripts/build
bash: ./scripts/build: No such file or directory
```

I see a `deps.edn` but don’t see how I’m supposed to run `clj` to run the tests :confused:

**Comment by bfontaine** [comment]
`clj -A:dev -m cuerdas.runner` appears to work but hits an NPE:
```
$ clj -A:dev -m cuerdas.runner

Testing cuerdas.core-tests

Ran 1 tests containing 288 assertions.
0 failures, 0 errors.
Exception in thread "main" java.lang.NullPointerException
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```
